site_name: ChatCraft Documentation
site_url: https://github.com/teaching-repositories/chatcraft
repo_url: https://github.com/teaching-repositories/chatcraft
repo_name: teaching-repositories/chatcraft
edit_uri: edit/main/docs/
theme:
  name: material
  favicon: assets/icon-192.png
  features:
    - navigation.tabs
    - navigation.instant
  palette:
    scheme: default
    primary: indigo
    accent: light blue
nav:
  - Home: index.md
  - Bots: bot-gallery.md
  - "Ollama Setup": ollama-guide.md
  - Education: education-guide.md
  - Projects: mini-projects.md
  - Template: mini-project-template.md
  - "ChatCraft CLI": cli-guide.md
  - RAG Guide: ragcraft-guide.md
  - Classroom: classroom-setup.md
  - Configuration: configuration.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["chatcraft"]
          options:
            docstring_style: google
            show_signature: false

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/teaching-repositories/chatcraft

extra_css:
  - stylesheets/custom.css

extra_javascript:
  - javascripts/custom.js

