site_name: AiLabKit Documentation
site_url: https://github.com/teaching-repositories/ailabkit
repo_url: https://github.com/teaching-repositories/ailabkit
repo_name: teaching-repositories/ailabkit
edit_uri: edit/main/docs/
theme:
  name: material
  favicon: assets/icon-192.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - toc.integrate
  palette:
    scheme: default
    primary: indigo
    accent: light blue
nav:
  - Home: index.md
  - Getting Started:
    - "Installation": configuration.md 
    - "Ollama Setup": ollama-guide.md
    - "Classroom Setup": classroom-setup.md
  - Modules:
    - Chat:
      - "Overview": chat-guide.md
      - "Bot Gallery": bot-gallery.md
      - "Bot Template": bot-template.md
      - "CLI Reference": cli-guide.md
    - RAG:
      - "Overview": rag-guide.md
      - "RAG Flow": rag-flow.md
      - "How RAG Works": rag-llm-explain.md
      - "CLI Reference": cli-guide.md
    - Agent:
      - "Overview": agent-guide.md
      - "Understanding Agents": agent-concepts.md
      - "Agent Modules": agent-agents.md
      - "Tool Reference": agent-tools.md
      - "CLI Reference": cli-guide.md
  - For Educators:
    - "Education Guide": education-guide.md
    - "Classroom Setup": classroom-setup.md
    - "Projects Overview": mini-projects.md
    - "Project Gallery": projects/index.md
    - "Project Template": mini-project-template.md
    - "Bot Template": bot-template.md
  - For Developers:
    - "Project Tools": project-tools.md
    - "CLI Reference": cli-guide.md
    - "Bot Template": bot-template.md
    - "Project Template": mini-project-template.md
    - "Contributing": contributing.md
  - Templates:
    - "Bot Template": bot-template.md
    - "Project Template": mini-project-template.md
  - About:
    - "Authors": authors.md
    - "Contributing": contributing.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["ailabkit"]
          options:
            docstring_style: google
            show_signature: false

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/teaching-repositories/ailabkit

extra_css:
  - stylesheets/custom.css

extra_javascript:
  - javascripts/custom.js

