site_name: HandsOnAI Documentation
site_url: https://teaching-repositories.github.io/hands-on-ai/
repo_url: https://github.com/teaching-repositories/hands-on-ai
repo_name: teaching-repositories/hands-on-ai
edit_uri: edit/main/docs/
theme:
  name: material
  favicon: assets/icon-192.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - toc.integrate
  palette:
    scheme: default
    primary: indigo
    accent: light blue
nav:
  - Home: index.md
  - Getting Started:
    - "Installation": configuration.md 
    - "Ollama Setup": ollama-guide.md
    - "Classroom Setup": classroom-setup.md
    - "LLM Guide": llm-guide.md
    - "Migration Guide": migration.md
  - Modules:
    - Chat:
      - "Overview": chat-guide.md
      - "Bot Gallery": bot-gallery.md
      - "Bot Template": bot-template.md
      - "CLI Reference": cli-guide.md
    - RAG:
      - "Overview": rag-guide.md
      - "RAG Flow": rag-flow.md
      - "How RAG Works": rag-llm-explain.md
      - "CLI Reference": cli-guide.md
    - Agent:
      - "Overview": agent-guide.md
      - "Understanding Agents": agent-concepts.md
      - "Agent Modules": agent-agents.md
      - "Tool Reference": agent-tools.md
      - "CLI Reference": cli-guide.md
  - For Educators:
    - "Education Guide": education-guide.md
    - "Classroom Setup": classroom-setup.md
    - "Projects Overview": mini-projects.md
    - "Project Gallery": projects/index.md
    - Agent Projects:
      - Agent Evaluation Framework: projects/agent/agent-evaluation-framework.md
      - Custom Tool Creator: projects/agent/custom-tool-creator.md
      - Date Calculator: projects/agent/date-calculator.md
      - Educational Assistant: projects/agent/educational-assistant.md
      - Multi-tool Problem Solver: projects/agent/multi-tool-problem-solver.md
      - Personal Math Tutor: projects/agent/personal-math-tutor.md
      - Science Explorer: projects/agent/science-explorer.md
      - Simple Calculator Agent: projects/agent/simple-calculator-agent.md
      - Text Analyzer: projects/agent/text-analyzer.md
      - Unit Conversion Assistant: projects/agent/unit-conversion-assistant.md
      - Word Detective: projects/agent/word-detective.md
    - Chat Projects:
      - Advanced Journal Bot: projects/chat/advanced-journal-bot.md
      - Bot Personality Menu Generator: projects/chat/bot-personality-menu-generator.md
      - Build Your Own Personality Bot: projects/chat/build-your-own-personality-bot.md
      - Choose Your Own Adventure: projects/chat/choose-your-own-adventure.md
      - Classroom Simulation Bot: projects/chat/classroom-simulation-bot.md
      - Code Explainer Tool: projects/chat/code-explainer-tool.md
      - Creative Writing Partner: projects/chat/creative-writing-partner.md
      - Data Visualization Dashboard: projects/chat/data-visualization-dashboard.md
      - Debate Interview Panel Dialogue Simulator: projects/chat/debate-interview-panel-dialogue-simulator.md
      - Emotional Support Bot: projects/chat/emotional-support-bot.md
      - Historical Figure Chat: projects/chat/historical-figure-chat.md
      - Image Gallery Creator: projects/chat/image-gallery-creator.md
      - Journal or Reflection Bot: projects/chat/journal-or-reflection-bot.md
      - Knowledge Quiz Bot: projects/chat/knowledge-quiz-bot.md
      - Language Translation Helper: projects/chat/language-translation-helper.md
      - Mood Journal Assistant: projects/chat/mood-journal-assistant.md
      - Personality Bot Creator: projects/chat/personality-bot-creator.md
      - Smart To-Do List: projects/chat/smart-to-do-list.md
      - Subject Expert Tutor: projects/chat/subject-expert-tutor.md
      - Text Adventure Game Engine: projects/chat/text-adventure-game-engine.md
      - Trivia or Quiz Bot: projects/chat/trivia-or-quiz-bot.md
      - Weather Dashboard: projects/chat/weather-dashboard.md
      - YouTube to Blog Converter: projects/chat/youtube-to-blog-converter.md
    - RAG Projects:
      - Build Your Own QA CLI: projects/rag/build-your-own-qa-cli.md
      - First RAG Bot: projects/rag/first-rag-bot.md
      - Hybrid Reasoning Bot: projects/rag/hybrid-reasoning-bot.md
      - PDF Question Answering Chatbot: projects/rag/pdf-question-answering-chatbot.md
    - "Project Template": mini-project-template.md
    - "Bot Template": bot-template.md
  - For Developers:
    - "Project Tools": project-tools.md
    - "CLI Reference": cli-guide.md
    - "Bot Template": bot-template.md
    - "Project Template": mini-project-template.md
    - "Contributing": contributing.md
  - Templates:
    - "Bot Template": bot-template.md
    - "Project Template": mini-project-template.md
  - About:
    - "Authors": authors.md
    - "Contributing": contributing.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["hands_on_ai"]
          options:
            docstring_style: google
            show_signature: false

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/teaching-repositories/hands-on-ai

extra_css:
  - stylesheets/custom.css

extra_javascript:
  - javascripts/custom.js

